### ISSUE TITLE
Norwegian language code for iOS is "nb", not "no"

### ISSUE THREAD

**Issue by mbuchetics** [chrztoph/texterify#22]
Xcode offers two options for Norwegian (Bokmå and Nynorsk), see also [Wikipedia](https://en.wikipedia.org/wiki/Norwegian_language#Bokmål_and_Nynorsk).

The folders used are `nb.lproj` and `nn.lproj`. Texterify currently exports Norwegian to `no.lproj`. It would be great to be able to define a configuration-specific mapping of language codes. Currently the solution is to rename or copy the exported folder.

**Comment by chrztoph** [comment]
This is now possible in the next release.
Thank you.
