### ISSUE TITLE
Fix Android Export

### ISSUE THREAD

**Issue by bleeding182** [chrztoph/texterify#31]
The Android export escapes characters way too aggressively breaking simple [HTML markup styling](https://developer.android.com/guide/topics/resources/string-resource#StylingWithHTML) (bold, italics, etc) for text.

**Observed behavior:**

When I input `Hello <b>World</b>!` (no "HTML" option) the export generates `Hello &lt;b&gt;World&lt;/b&gt;!`.

**Expected behavior:**

It should generate `Hello <b>World</b>!`

When a string is not marked as HTML I expect to receive the same String in the output (with _some_ [special characters escaped](https://developer.android.com/guide/topics/resources/string-resource#escaping_quotes))

**Comment by chrztoph** [comment]
Fixed. Thank you!
